/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as RemoteLaunchRouteImport } from './routes/remote-launch'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects.$projectId.index'
import { Route as ProjectsProjectIdSkillsRouteImport } from './routes/projects.$projectId.skills'
import { Route as ProjectsProjectIdSettingsTabRouteImport } from './routes/projects.$projectId.settings.$tab'
import { Route as ProjectsProjectIdTasksSessionIdRouteImport } from './routes/projects.$projectId.tasks.$sessionId'
import { Route as ProjectsProjectIdTasksNewRouteImport } from './routes/projects.$projectId.tasks.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoteLaunchRoute = RemoteLaunchRouteImport.update({
  id: '/remote-launch',
  path: '/remote-launch',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdSkillsRoute = ProjectsProjectIdSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdSettingsTabRoute =
  ProjectsProjectIdSettingsTabRouteImport.update({
    id: '/settings/$tab',
    path: '/settings/$tab',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdTasksSessionIdRoute =
  ProjectsProjectIdTasksSessionIdRouteImport.update({
    id: '/tasks/$sessionId',
    path: '/tasks/$sessionId',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdTasksNewRoute =
  ProjectsProjectIdTasksNewRouteImport.update({
    id: '/tasks/new',
    path: '/tasks/new',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/remote-launch': typeof RemoteLaunchRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/skills': typeof ProjectsProjectIdSkillsRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/settings/$tab': typeof ProjectsProjectIdSettingsTabRoute
  '/projects/$projectId/tasks/$sessionId': typeof ProjectsProjectIdTasksSessionIdRoute
  '/projects/$projectId/tasks/new': typeof ProjectsProjectIdTasksNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/remote-launch': typeof RemoteLaunchRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/skills': typeof ProjectsProjectIdSkillsRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/settings/$tab': typeof ProjectsProjectIdSettingsTabRoute
  '/projects/$projectId/tasks/$sessionId': typeof ProjectsProjectIdTasksSessionIdRoute
  '/projects/$projectId/tasks/new': typeof ProjectsProjectIdTasksNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/remote-launch': typeof RemoteLaunchRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/skills': typeof ProjectsProjectIdSkillsRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/settings/$tab': typeof ProjectsProjectIdSettingsTabRoute
  '/projects/$projectId/tasks/$sessionId': typeof ProjectsProjectIdTasksSessionIdRoute
  '/projects/$projectId/tasks/new': typeof ProjectsProjectIdTasksNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects'
    | '/remote-launch'
    | '/projects/$projectId'
    | '/projects/'
    | '/projects/$projectId/skills'
    | '/projects/$projectId/'
    | '/projects/$projectId/settings/$tab'
    | '/projects/$projectId/tasks/$sessionId'
    | '/projects/$projectId/tasks/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/remote-launch'
    | '/projects'
    | '/projects/$projectId/skills'
    | '/projects/$projectId'
    | '/projects/$projectId/settings/$tab'
    | '/projects/$projectId/tasks/$sessionId'
    | '/projects/$projectId/tasks/new'
  id:
    | '__root__'
    | '/'
    | '/projects'
    | '/remote-launch'
    | '/projects/$projectId'
    | '/projects/'
    | '/projects/$projectId/skills'
    | '/projects/$projectId/'
    | '/projects/$projectId/settings/$tab'
    | '/projects/$projectId/tasks/$sessionId'
    | '/projects/$projectId/tasks/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  RemoteLaunchRoute: typeof RemoteLaunchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remote-launch': {
      id: '/remote-launch'
      path: '/remote-launch'
      fullPath: '/remote-launch'
      preLoaderRoute: typeof RemoteLaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/skills': {
      id: '/projects/$projectId/skills'
      path: '/skills'
      fullPath: '/projects/$projectId/skills'
      preLoaderRoute: typeof ProjectsProjectIdSkillsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/settings/$tab': {
      id: '/projects/$projectId/settings/$tab'
      path: '/settings/$tab'
      fullPath: '/projects/$projectId/settings/$tab'
      preLoaderRoute: typeof ProjectsProjectIdSettingsTabRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/tasks/$sessionId': {
      id: '/projects/$projectId/tasks/$sessionId'
      path: '/tasks/$sessionId'
      fullPath: '/projects/$projectId/tasks/$sessionId'
      preLoaderRoute: typeof ProjectsProjectIdTasksSessionIdRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/tasks/new': {
      id: '/projects/$projectId/tasks/new'
      path: '/tasks/new'
      fullPath: '/projects/$projectId/tasks/new'
      preLoaderRoute: typeof ProjectsProjectIdTasksNewRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
  }
}

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdSkillsRoute: typeof ProjectsProjectIdSkillsRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
  ProjectsProjectIdSettingsTabRoute: typeof ProjectsProjectIdSettingsTabRoute
  ProjectsProjectIdTasksSessionIdRoute: typeof ProjectsProjectIdTasksSessionIdRoute
  ProjectsProjectIdTasksNewRoute: typeof ProjectsProjectIdTasksNewRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdSkillsRoute: ProjectsProjectIdSkillsRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
  ProjectsProjectIdSettingsTabRoute: ProjectsProjectIdSettingsTabRoute,
  ProjectsProjectIdTasksSessionIdRoute: ProjectsProjectIdTasksSessionIdRoute,
  ProjectsProjectIdTasksNewRoute: ProjectsProjectIdTasksNewRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  RemoteLaunchRoute: RemoteLaunchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
